version: 2

python:
  install:
    - method: pip
      path: .
      dependency_groups:
        - docs
      extra_requirements:
        - all

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#   - pdf
#   - epub

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
